### ISSUE TITLE
Allow sending target domain name when no other referer would be sent

### ISSUE THREAD

**Issue by tgh1** [meh/smart-referer#10]
I have mode set to self but for images no referer is being sent at all, so i'm getting 403s & no hotlinking messages

**Comment by boxcars-at-gmx-dot-net** [comment]
It would be good to have domain-name-only as an option for times when no referrer would otherwise be sent and as an option for whitelisted sites.

**Comment by alexander255** [comment]
Is this still an issue/relevant anywhere? If so, could you give an example of where this would be relevant? Thanks!

**Comment by alexander255** [comment]
Closing for no response.
