### ISSUE TITLE
Can't play video on ebc.net.tw

### ISSUE THREAD

**Issue by ReporterX** [meh/smart-referer#101]
[https://news.ebc.net.tw/news.php?nid=123251](https://news.ebc.net.tw/news.php?nid=123251)

You can't play the video if the addon is turned on.

**Comment by alexander255** [comment]
Apparently YouTube has referer authentication now as well. :roll_eyes:
Anyways, please test to make sure it works as expected:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure you use the default **Whitelist Source** (`http://meh.github.io/smart-referer/whitelist.txt`)
 5. Remove any custom **Allow** rules that are related to this bug
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the *Enable* to re-enable button (this will force a whitelist update)
 8. Check if your page is working now 🙂 

Feel free to close this issue if it works now!

**Comment by ReporterX** [comment]
I followed the above guideline but it does not work. It said "the video is unavailable" when I clicked on the video. I tried it three times.

**Comment by alexander255** [comment]
Weird, I noticed that the guide had been slightly wrong/outdated however. :sweat_smile: 

Is the default whitelist enabled in the settings?
If you manually add an exception for source `news.ebc.net.tw`and destination `www.youtube.com`, does it work then? If not, could you please gather some debugging based on the [new guide in the Wiki](https://github.com/meh/smart-referer/wiki/Gathering-Data-for-Whitelist-Entries)?

Sorry, 'bout this but it does work for me.

**Comment by ReporterX** [comment]
It works now. Perhaps it failed to update the whitelist for unknown reasons the last time I tried.
