### ISSUE TITLE
[Whitelist] disney-channel (de) does not work completely

### ISSUE THREAD

**Issue by DJCrashdummy** [meh/smart-referer#104]
at least the live stream from [disney-channel (de)](https://tv.disney.de/disney-channel) does not play with smart-referer enabled.

i managed to get it working with adding `tv.disney.de>*.akamaihd.net` to the exceptions.

**Comment by alexander255** [comment]
Thanks for your feedback.
I've tested, verified and added the suggested rule. Thank you for your help!

Please test to make sure it works as expected:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure you use the default **Whitelist Source** (`http://meh.github.io/smart-referer/whitelist.txt`)
 5. Remove any custom **Allow** rules that are related to this bug
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the *Enable* to re-enable button (this will force a whitelist update)
 8. Check if your page is working now 🙂 

Feel free to close this issue if it works now!

**Comment by DJCrashdummy** [comment]
btw: isn't the default whitelist-url https://raw.githubusercontent.com/meh/smart-referer/gh-pages/whitelist.txt?

**Comment by alexander255** [comment]
Yes, I just noticed and updated the reply template. In recent versions the “default whitelist” is now simply a checkbox, no need to even mention the URL anymore. :slightly_smiling_face:

**Comment by alexander255** [comment]
Dann is ja nix passiert. :slightly_smiling_face: 
LG aus Graz

**Comment by DJCrashdummy** [comment]
https://tv.disney.de/disney-channel does not work anymore with smart-referer enabled... probably it is because of #110 (if this issue also applies to the default whitelist?). if not, maybe this issue needs to be reopened.

**Comment by alexander255** [comment]
Should work with the latest update again. Sorry for the inconvenience!

**Comment by DJCrashdummy** [comment]
no harm done, it works again. thank you @alexander255!
