### ISSUE TITLE
[Feature request] A checkbox for the extension to rewrite the referer even if the source and target domain are the same

### ISSUE THREAD

**Issue by RusselsTeaPot69** [meh/smart-referer#108]
Instead of only when changing domains. I have used this configuration for years with other referrer extensions with a short personal whitelist of only 7 domains causing problems with same-domain referrer spoofing, it wasn't the massive breakage one could expect, and I suggest it would be unchecked by default anyway.
RefControl is legacy and Referer Control doesn't work, this is the only good extension dedicated to referrer I know of, yet I have to use Header Editor (which is not very practical) to be able to spoof the referrer everywhere because this is not possible here.

**Comment by alexander255** [comment]
What you describe sounds exactly like the „Strict Mode“ checkbox in *Smart Referer*'s options. Does this do what you'd expect? If yes, do think there would be a more appropriate description for this feature?

**Comment by RusselsTeaPot69** [comment]
The strict mode as I understand it treats a.example.com as a domain different from example.com and will spoof when going from one to the other. However when going from a www.example.com to the exact same full domain www.example.com, the referrer will not be spoofed, strict mode or not. I just tested that it's not spoofed, here:
http://www.stardrifter.org/refcontrol/
when clicking on the link "Test page" at the bottom of the page (so going from www.stardrifter.org to the same full domain).

There should be a third mode to allow spoofing also in the case of same full domain for source and target, that means spoofing all the time (except the whitelist sites of course). Well maybe not a checkbox exactly, but a mutually exclusive list of choices between standard mode, strict mode and the new mode. There could be a warning of higher breakage with this new mode, that the whitelist won't support it and so on, possibly.

**Comment by alexander255** [comment]
Thanks for clearing that up! While I don't see any particular benefit in this, I do accept that such an option is currently missing and may be useful in some cases.

**Comment by ntninja** [comment]
This issue has been moved to GitLab: https://gitlab.com/smart-referer/smart-referer/issues/108
