### ISSUE TITLE
Exceptions do not work anymore

### ISSUE THREAD

**Issue by ThisIsABug** [meh/smart-referer#110]
I use Firefox (62.0) and smart-referer since a long time, works really well, I have one exception in my list:
*.visualstudio.com -> *.timehub.7pace.com
This does not work anymore since todays update of the addon.
When I look into the console I can see that while using Azure DevOps (visualstudio.com) with 7pace Timetracker (timehub.7pace.com) that the sent request header is the same as the requested url.
My rewrite mode is set to recommended.
(i hope it is reproduceable on any host)

**Comment by ellypsis** [comment]
I also have a problem with facebook video.
I added the rule *.facebook.com -> *.fbcdn.net but it's not working.
Seems to be because of the upgrade.

**Comment by Ythan** [comment]
Changing the rewrite mode to "send nothing as referer, looking like a direct hit" will allow Facebook videos to work again, but it may break other sites. I hope exceptions will be fixed in the next release.

**Comment by alexander255** [comment]
Fixed by @takamichih in #111.

**Comment by Dagrut** [comment]
It does not work for me (Firefox 60.2.0esr, Smart Referer 0.2.10, Debian 9.5). I'm trying on https://messages.android.com/ but the XHR query to instantmessaging-pa.googleapis.com fails.

**Comment by alexander255** [comment]
@Dagrut: I tested this on the exact same system configuration you mentioned and see no problems at all. Does it work when you disable *Smart Referer* entirely (click on the icon or simply disable the extension)? Do you have tracking protection enabled on this site?

**Comment by Dagrut** [comment]
Okay, I don't know how, but removing and installing it fixed the problem :-)

(I first tried with a new firefox profile, and it worked too). There must have been some cache files that were blocking it somewhere. Thanks! :-D
