### ISSUE TITLE
visa-signature.com broken

### ISSUE THREAD

**Issue by ReporterX** [meh/smart-referer#112]
https://www.visa-signature.com/Gateway
The "Country" dropdown list cannot be shown if it is on.

https://www.visa.com.hk/en_HK/pay-with-visa/find-a-card/visa-signature.html#3
The "Offers" section cannot be shown properly if it is on.

**Comment by alexander255** [comment]
Thanks for your feedback!
I cannot reproduce the first issue: The country list is always shown (and all relevant connections are to `visa.com` only anyways).
The second issue is likely `*.visa.com.hk>*.visa.hk`. It also works when changing *Rewrite Mode* to *Send empty Referer* – I will investigate making this the default (#113) as it looks like many pages that do referer checking handle this value more correctly.

**Comment by ReporterX** [comment]
It works again in the first case. I believe it was simply because the dropdown list failed to generate after I selected the region. Smart referrer appeared to be the culprit when I disabled, refreshed the page and tried for the second time. The first one could be closed.

It still doesn't work even I added `*.visa.com.hk>*.visa.hk` in the second case.

**Comment by alexander255** [comment]
Sorry, I messed up the rule, it was supposed to be `*.visa.com.hk>*.visa.com`. `visa.hk` is not really for sale at this time :stuck_out_tongue_closed_eyes:

**Comment by ReporterX** [comment]
Haha I see. That exception rule works as expected. Thank you very much.

**Comment by alexander255** [comment]
Thanks for the feedback! I've pushed the rule to the default whitelist now.
