### ISSUE TITLE
Add Vanguard API to whitelist?

### ISSUE THREAD

**Issue by kevinoid** [meh/smart-referer#116]
If Smart Referer is configured with "Rewrite Mode" "Send nothing ..." and "Strict Mode" is enabled, the Vanguard mutual fund information fails to load.  For example, https://investor.vanguard.com/mutual-funds/profile/VTSAX makes a request for https://api.vanguard.com/rs/ire/01/ind/fund/VTSAX/profile.jsonp?callback=angular.callbacks._0&planId=null which fails with 400 "We're sorry. The page you requested could not be found. ...".  Adding `investor.vanguard.com>api.vanguard.com` fixes the issue and the information loads correctly.

I'm not sure how you feel about whitelist entries which are only required for non-default settings.  I assume there is a lot of breakage with those settings.  (I actually discovered it using `network.http.referer.XOriginPolicy`.)  If it's not worth whitelisting, feel free to close.

Also note that the other vanguard subdomains listed on https://investor.vanguard.com/corporate-portal/ are probably affected, although I couldn't find specific examples.  Adding `*.vanguard.com>api.vanguard.com` may be wise.

Thanks for considering,
Kevin

**Comment by ntninja** [comment]
Thank you for your feedback! As you have guessed however, we do not add whitelist rules for breakage only occurring in strict mode, as we assume that there is no privacy benefit in enabling this mode. I have pushed an update to the extension preferences (613293d5d052245bd9255bf0813fb3b0cd01d614) to clarify this.
