### ISSUE TITLE
Images fail to display if Smart Referer is enabled

### ISSUE THREAD

**Issue by ReporterX** [meh/smart-referer#20]
Try to type any term in the search engine. None can be shown in the search result page if Smart Referer is enabled:
http://image.baidu.com/

Or simply click this search link: 
http://image.baidu.com/i?tn=baiduimage&ipn=r&ct=201326592&cl=2&lm=-1&st=-1&fm=index&fr=&sf=1&fmq=&pv=&ic=0&nc=1&z=&se=1&showtab=0&fb=0&width=&height=&face=0&istype=2&ie=utf-8&word=photo&oq=photo&rsp=-1

**Comment by alexander255** [comment]
baidu.com image search now references its images from bdstatic.com, which doesn't apparently do any referer checking.
