### ISSUE TITLE
[whitelist] ok.ru

### ISSUE THREAD

**Issue by lainverse** [meh/smart-referer#24]
Blocks pictures in various places.
Example: http://ok.ru/gifts
Fix: ok.ru>* or st.mycdn.me

**Comment by alexander255** [comment]
Fixed!

Please test to make sure it works as expected:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure you use the default **Whitelist Source** (`http://meh.github.io/smart-referer/whitelist.txt`)
 5. Remove any custom **Allow** rules that are related to this bug
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the *Enable* to re-enable button (this will force a whitelist update)
 8. Check if your page is working now :-)

Feel free to close this issue if it works now!

**Comment by lainverse** [comment]
Seems fine, thanks.

**Comment by alexander255** [comment]
Hi! I've just retested this rule and it appears to no longer be necessary on this site anymore and will therefor be **removed from the whitelist**.
Please reopen this issue if you experience problems due to this.
