### ISSUE TITLE
Display the referer that the browser is sending

### ISSUE THREAD

**Issue by ReporterX** [meh/smart-referer#26]
It would be great if the addon can display the URL (referer) the browser is sending in the toolbar. Something like this:

![Display referer](http://snag.gy/u8jXT.jpg)

So I can see if the addon works as expected, or test to see if the custom entries added in the "Allow" list is working etc.

**Comment by alexander255** [comment]
How would that help? Referers usually cause issues for object embedded into the page (not for the page you are trying to load itself) and can be seen using the *Network Monitor*.
Are you suggesting something like "5 referers changed on this page" with more details (the URL of every item in the page that had it's referer modified) when clicking on the text/button?

**Comment by ReporterX** [comment]
Yes, something like that.
It is actually a screenshot from another addon RefControl, but it is very basic.

Network monitor is a great tool, although most users don't know its existence. I'm still learning how to make use of it.
I have to type referer in the "filter" box each time to quickly see the referer info for each request.
I'm not sure if it is possible to output a list of referers sent for all requests.

**Comment by ntninja** [comment]
This issue has been moved to GitLab: https://gitlab.com/smart-referer/smart-referer/issues/26
