### ISSUE TITLE
A button to toggle the addon on/off

### ISSUE THREAD

**Issue by ReporterX** [meh/smart-referer#27]
I know there is an addon called "Custom Buttons", but the button image does not change when you toggle the addon on and off.
It is still a hassle to users if they need to add this basic function themselves.
Sometimes we need to switch it off when you visit a website which has complicated referer checking.
It is better to provide a button by the addon itself, instead of seeking help from a third-party addon.

**Comment by alexander255** [comment]
Ping @meh 
Please look into this :-)

**Comment by alexander255** [comment]
@meh Would you accept a pull request that implements this?

**Comment by meh** [comment]
@alexander255 if it doesn't make the code way more complex because of XUL or whatever, sure.

**Comment by alexander255** [comment]
Is it OK if I'm loading the button via the Add-on SDK? The existing code would have to be ported to a SDK module, but the changes to the existing code would be minimal nevertheless. I'd estimate about 50 to 200 extra lines of code. Would that be OK with you?

**Comment by meh** [comment]
Ehhh, that much code for just a button sounds lame.

Would you be able to add some UI stuff for the whitelist too? If that's the case I'd be okay with that increase.

**Comment by alexander255** [comment]
Fixed by our switch to WebExtensions (#48)
