### ISSUE TITLE
Fail to load images in dm5.com

### ISSUE THREAD

**Issue by ReporterX** [meh/smart-referer#28]
http://www.dm5.com/m4029/

It has referer checking. It will show a warning image (an angry girl with yellow hair) that you are not on its own website when you view their images.

**Comment by alexander255** [comment]
That was easy シ

A whitelist update is now available!

Please test to make sure it works as expected:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure you use the default **Whitelist Source** (`http://meh.github.io/smart-referer/whitelist.txt`)
 5. Remove any custom **Allow** rules that are related to this bug
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the *Enable* to re-enable button (this will force a whitelist update)
 8. Check if your page is working now :-)

Feel free to close this issue if it works now!

**Comment by ReporterX** [comment]
Yes it works great!
