### ISSUE TITLE
Can't play video at tvmost

### ISSUE THREAD

**Issue by ReporterX** [meh/smart-referer#29]
http://www.tvmost.com.hk/

It has referer checking.

**Comment by alexander255** [comment]
Playback works fine for me both with and without *Smart Referer*. Enabling a proxy (ZenMate Hong Kong) will cause all video frames to be replaced by an `403 Forbidden` error message however. Enabling/disabling flash had no influence.
Testing was mainly done using this video: http://www.tvmost.com.hk/201505222027_video_dogdays_03 (wtf are they doing, btw?)

Could you please provide the address of a page that does not work with *Smart Referer* but works without it?

**Comment by ReporterX** [comment]
Change the mode into "Send nothing as referer, looking like a direct hit"
Visit the page again. You should see a complaint: "Sorry Because of its privacy settings, this video cannot be played here."

P.S. The video is a parody of a TV series

**Comment by alexander255** [comment]
Should be fixed now, thanks for pointing out that you changed the *Mode* setting!


A whitelist update is now available!

Please test to make sure it works as expected:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure you use the default **Whitelist Source** (`http://meh.github.io/smart-referer/whitelist.txt`)
 5. Remove any custom **Allow** rules that are related to this bug
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the *Enable* to re-enable button (this will force a whitelist update)
 8. Check if your page is working now :-)

Feel free to close this issue if it works now!
