### ISSUE TITLE
Does this affect CSRF?

### ISSUE THREAD

**Issue by rdsubhas** [meh/smart-referer#30]
Love this addon! But since its setting HTTP-Referer to empty (direct hit) or target site, does it affect CSRF? Do cross site requests just go ahead because the Referer tag now seems legit? Or do requests still obey the content policy?

Could be a dumb question, but would be nice if you can clarify it on the home page :)

Thanks!

**Comment by meh** [comment]
It doesn't affect CSRF.

**Comment by alexander255** [comment]
It *might* affect the CSRF protection of some sites, if those sites:

 * Exclusively rely on the HTTP `Referer` header for CSRF detection (i.e.: they don't use cookies or hidden form fields for verification at all)
 * Treat empty referers as valid values for the HTTP `Referer` header

A set up like this is pretty rare (and is usually considered insecure), but there are definitely some sites out there that do things this way (its possible and a bad idea -> somebody definitely did it).

On the other hand: The number of pages that are *more vulnerable* thanks to this add-on is probably pretty insignificant to the number of pages that *don't have any protection* and to the number of pages that have *proper protection*.

I never thought about this before, but, now that I did, I think that the benefits provided by *Smart Referer* (in terms of privacy) definitely outweigh these (minor) risks. (remember: An attacker has to know that a site and user are vulnerable before he attempts the attack and has to think that the target audience is big enough for the attack to be worth it.)

Compared to many other thinks your web browser does (like executing JavaScript), the extra risk posed by this is pretty much near zero (just my opionion).
