### ISSUE TITLE
[NSFW] Video often blocked on xhamster.com

### ISSUE THREAD

**Issue by lainverse** [meh/smart-referer#32]
Suggested exceptions: xhamster.com>\* \*.xhamster.com>\*
Could be better to whitelist video-hosting services used there, though.

BTW, is it possible to whitelist domain _and_ subdomains at once to cover cases like address with and without "www."?

**Comment by alexander255** [comment]
I couldn't reproduce the issue on the videos I tried. Do you have a list of video services that are affected (with example links)? Would such a list be likely to change often? I'm a bit uncomfortable with adding "*" when it's not necessary.

Unfortunately matching both "www.bla.tld" and "bla.tld" with one rule is not possible and would require a code update. I might add support for that when I implement feature #27, but that's not going to happen tomorrow…

**Comment by lainverse** [comment]
Nevermind, seems like they removed that player or removed check for referrer.
