### ISSUE TITLE
Request for *.typography.com to be added to the whitelist

### ISSUE THREAD

**Issue by Oosik** [meh/smart-referer#35]
So I've been banging my head against the wall for a couple hours now. turns out I needed to whitelist: *.typography.com to get Hoefler & Co fonts to work. You might want to add it to the whitelist.

Thanks

**Comment by alexander255** [comment]
The whitelist has been updated! Thanks for reporting this and sorry for the trouble this may have caused you!

Please test to make sure it works as expected:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure you use the default **Whitelist Source** (`http://meh.github.io/smart-referer/whitelist.txt`)
 5. Remove any custom **Allow** rules that are related to this bug
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the *Enable* to re-enable button (this will force a whitelist update)
 8. Check if your page is working now :-)

Feel free to close this issue if it works now!

**Comment by alexander255** [comment]
It appears this whitelist entry is no longer necessary. Removing from whitelist.
