### ISSUE TITLE
Vivocha.com Online Help not working on HKTVmall.com

### ISSUE THREAD

**Issue by ReporterX** [meh/smart-referer#36]
http://www.hktvmall.com/hktv/en/faq

This tab (Online Help) does not show up if Smart Referer is enabled.
![HKTVmall Online Help Assistance] (http://snag.gy/rqPq0.jpg)

It appears this tab only shows up in business hours. It should be around 9am - 7pm (GMT+8), so you need to check at that period.

**Comment by alexander255** [comment]
Thanks for reporting this, unfortunately that is 2 - 12 am in my time zone :-(
I'll catch it eventually through... :+1:

**Comment by alexander255** [comment]
Should be fixed now :smile_cat: 

You know the drill :wink: :

Please test to make sure it works as expected:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure you use the default **Whitelist Source** (`http://meh.github.io/smart-referer/whitelist.txt`)
 5. Remove any custom **Allow** rules that are related to this bug
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the *Enable* to re-enable button (this will force a whitelist update)
 8. Check if your page is working now :-)

Feel free to close this issue if it works now!

**Comment by ReporterX** [comment]
Yes confirmed. It is working now.
