### ISSUE TITLE
In Firefox 28 and above, read/write built-in preferences for referers

### ISSUE THREAD

**Issue by ipatjolvur** [meh/smart-referer#38]
[One of the comments](https://addons.mozilla.org/en-US/firefox/addon/smart-referer/reviews/570470/) on the Mozilla Addons page for Smart Referer:

> _Works flawlessly, but Firefox 28 has (hidden) preferences for this!_
> _by [JeremiasFromHere](https://addons.mozilla.org/en-US/firefox/user/JeremiasFromHere/) on April 2, 2014_
> 
> Since Firefox 28 there are three new items in `about:config`:
> 
> `network.http.referer.XOriginPolicy`: 0=always send, 1=send if base domains match, 2=send if hosts match
> `network.http.referer.spoofSource`: false=real referer, true=spoof referer (use target URI as referer)
> `network.http.referer.trimmingPolicy`: 0=send full URI, 1=scheme+host+port+path, 2=scheme+host+port
> 
> Referrer processing is done in this order. Thus, setting XOriginPolicy to 2 makes spoofSource and trimmingPolicy useless if going from a.example.com to b.example.com, since no referrer would be send anyway due to the XOriginPolicy.
> 
> If using the three new I'd suggest to set the old network.http.sendRefererHeader to 2 (default, always send referrer).
> 
> See [https://bugzilla.mozilla.org/show_bug.cgi?id=822869](https://bugzilla.mozilla.org/show_bug.cgi?id=822869)

Smart Referer's `strict` mode looks like it behaves the way toggling between 1 and 2 for the built-in `XOriginPolicy` would.  Smart Referer looks like it always behaves the way <strike>`spoofSource = true` and</strike> `trimmingPolicy = 0` do.  Its `self` mode behaves like `spoofSource = true`. None of the three built-in options are on Firefox's Options/Preferences interface, but they could be added to Smart Referer's option pane due to their relevance.  If their behavior is the same, the built-in variables could be preferred over Smart Referer's analogues or completely replace them.

Your whitelist combined with the built-in options would provide the most configurable setup for users.  Since Mozilla is obviously thinking about referer security, I would go so far as to say I wish Smart Referer would be built into the mainline browser.  They have added other hidden-beta options that behave like EFF's Privacy Badger: `privacy.trackingprotection`

**Comment by alexander255** [comment]
Modern versions of Mozilla's browser don't allow this kind of interaction anymore. Closing won't fix.
