### ISSUE TITLE
gentside, ohmymag, maxisciences, ohmymag & exclusivomen

### ISSUE THREAD

**Issue by SMed79** [meh/smart-referer#42]
Hi, 

i noticed that all "cerise media" sites require an exception to play videos:

```
exclusivomen.com
gentside.com
gentside.com.br
gentside.de
maxisciences.com
ohmirevista.com
ohmymag.com
ohmymag.com.br
ohmymag.de
simplyvoyage.com
```

Best,
M.

**Comment by alexander255** [comment]
Fixed using https://forums.lanik.us/viewtopic.php?f=91&t=26060#p79271 .

Please test to make sure it works as expected:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure you use the default **Whitelist Source** (`http://meh.github.io/smart-referer/whitelist.txt`)
 5. Remove any custom **Allow** rules that are related to this bug
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the *Enable* to re-enable button (this will force a whitelist update)
 8. Check if your page is working now :-)

Feel free to close this issue if it works now!

**Comment by SMed79** [comment]
It works without disabling **Smart Referer**.

Note: the source of these domains is `secret media`, used to display pre-roll ad (fixed by **Liste FR**) can be changed at any time. Currently the only one used is `palmshapednontransferable.com` and the others are obsolet and can be removed.

 thank you.

**Comment by alexander255** [comment]
Hi! I've just retested this rule and it appears to no longer be necessary on this site anymore and will therefor be **removed from the whitelist**.
Please reopen this issue if you experience problems due to this.
