### ISSUE TITLE
website lachainemeteo.com 

### ISSUE THREAD

**Issue by smith330** [meh/smart-referer#45]
If adblock is enabled video don't start and content is not full.
Whitch filter add for this website? I don't disabled adblock 

Edit move to reek anti adblock forum part

**Comment by alexander255** [comment]
This issue is confusing to me, so I didn't look at lachainemeteo.com yet.

Please tell me first:

 * Is this issue about *Anti-AdBlock Killer* (by *reek*), or about *Smart Referer* (by *meh*)?
 * Does *lachainemeteo.com* video break, because of *Smart Referer*?

**Comment by smith330** [comment]
Yes it's issue for anti adblock i have edited move to anti adblock part forum

**Comment by alexander255** [comment]
I see you have already created reek/anti-adblock-killer#2089 … I'll close this issue then.
