### ISSUE TITLE
Page causes Firefox to freeze

### ISSUE THREAD

**Issue by Aspartaco** [meh/smart-referer#57]
The page linked below is a NSFW forum thread full of text and links, and it causes Firefox to freeze if Smart Referer is enabled and hardware accelleration is disabled.

https://www.akiba-online.com/threads/filejoker-may-2017-contest-tracking-thread.1732315/

I have a Ryzen 7 processor, so it's not a matter of system performance.

**Comment by MaxXor** [comment]
I can reproduce this issue on Windows 7 with Firefox 55.0.2 (64bit). It's only happening when Smart Referer is enabled.

**Comment by 5TDg9** [comment]
i **cannot** reproduce this with Win 8.1 Firefox 58.0.2.  Be careful whit the link, it's full of advertising and maybe also malvertising. I cannot check for malvertising at the moment, but maybe @Aspartaco will tell us more about the link he posted.

**Comment by Remu-rin** [comment]
Related bug with another test link (nsfw too though, but with 6000 connections instead of 2000): https://bugzilla.mozilla.org/show_bug.cgi?id=1400534

**Comment by ntninja** [comment]
This issue has been moved to GitLab: https://gitlab.com/smart-referer/smart-referer/issues/57
