### ISSUE TITLE
Smart Referer 0.2.2 bugfix release

### ISSUE THREAD

**Issue by alexander255** [meh/smart-referer#63]
@meh: Please release the changes I have just pushed to master.
Due to a stupid mistake of mine the whitelist mechanism currently effectively broken (it will only match when the source and target matching patterns are reversed in the rule). No other changes where done.

**Comment by Gitoffthelawn** [comment]
@meh Can you give @alexander255 more privileges to do this sort of thing directly?

**Comment by meh** [comment]
@Gitoffthelawn it's actually already in queue, 126 of 146.

**Comment by alexander255** [comment]
@meh Thanks!
