### ISSUE TITLE
0.2.3 sends referrer

### ISSUE THREAD

**Issue by Luke-Baker** [meh/smart-referer#65]
Firefox 56.0 / Nightly 58.0a1 20171007100142  
Smart Referer 0.2.3
New Firefox profile

Enable Smart Referer: yes
Strict mode: on or off makes no difference
Exceptions: none
Whitelist source: blank
Rewrite mode: Send nothing

Browser console shows the referrer is still being sent.

**Comment by alexander255** [comment]
Hi and thanks for your feedback!

Could you maybe provide an example URL and a screenshot of the offending behavior? Please note however that Smart Referer does not modify the referer in any way when loading resources from the same origin (i.e.: `https://www.example.com/demo.png` will receive the full referer when being embedded by `https://www.example.com/demo/`).

**Comment by Luke-Baker** [comment]
My mistake 😳 I tried several referrer add-ons in a short span and I didn't notice this one is supposed to always send the referrer when on the same domain. I can see now the referrer is indeed missing when not on the same domain.
