### ISSUE TITLE
solvemedia.com

### ISSUE THREAD

**Issue by SMed79** [meh/smart-referer#66]
Hi, 

add
```
*>api.solvemedia.com
*>api-secure.solvemedia.com
```

test at
```
https://u2s.io/lUG5j
http://adbilty.me/Rd73vE
```

**Comment by alexander255** [comment]
Thanks for reporting this and sorry for the inconvinience this may have caused. The entry had gotten removed along with the other entries of the legacy whitelist (#53), as there had been no information or response on where it was still used. Anyways, please test to make sure it works as expected:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure you use the default **Whitelist Source** (`http://meh.github.io/smart-referer/whitelist.txt`)
 5. Remove any custom **Allow** rules that are related to this bug
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the *Enable* to re-enable button (this will force a whitelist update)
 8. Check if your page is working now :-)

And (as usual) close this issue if it works as expected now! Thanks!

**Comment by SMed79** [comment]
Thanks, it works.
