### ISSUE TITLE
fanfiction.net

### ISSUE THREAD

**Issue by kah0922** [meh/smart-referer#67]
fanfiction.net needs to send the referrer to netdna-ssl.com in order to display covers, so:

Add *.fanfiction.net -> *.netdna-ssl.com

**Comment by alexander255** [comment]
Sorry for the delay! I got kinda lost on that site… 😁 

Please test to make sure it works as expected:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure you use the default **Whitelist Source** (`http://meh.github.io/smart-referer/whitelist.txt`)
 5. Remove any custom **Allow** rules that are related to this bug
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the *Enable* to re-enable button (this will force a whitelist update)
 8. Check if your page is working now 🙂 

Feel free to close this issue if it works now!

**Comment by kah0922** [comment]
It works now, thanks.
