### ISSUE TITLE
blocks weebly.com to show website to edit

### ISSUE THREAD

**Issue by chmike** [meh/smart-referer#68]
I have a web site on www.weebly.com. When smart-redirect is activated, I can't edit the site. I get a constant loading spinning wheel. When disabling smart-referer, the blocking is removed.
Obviously, stripping off the referrer field breaks the weebly site. 

The problem is that the domain displayed on the url bar is always www.weebly.com. 
I'm not seeing any redirect to another domain. So I don't know what to suggest to add to the whitelist.

**Comment by alexander255** [comment]
Thanks for reporting this issue!

Could you open the network analyser panel (Ctrl+Shift+E) on that site, reload the page and upload a screenshot of the result? It should look similar to this (make the panel as large before taking the screenshot, if the content still doesn't fit into the panel, please take one screenshot per page and post all of them):
![screenshot_20171031_203708](https://user-images.githubusercontent.com/246386/32245194-46c45428-be7b-11e7-840d-758f20774af9.png)

**Comment by chmike** [comment]
Thanks for the recipe. The list is very long. Not good. I needed three screen captures. See [here](https://imgur.com/a/noNwZ). 

It could be `*.editmysite.com` and `*.weebly.com` that depend on referrer. What do I have to do to fix the problem ?

**Comment by chmike** [comment]
I see two files with "not found" flags. One is on `...weebly.com`, and the other on `...preview.editmysite.com`. The `...editmysite.com` domain is part of the weebly infrastructure. See [this message](https://community.weebly.com/t5/Getting-Started/What-is-EditMySite-com/td-p/2042).

**Comment by chmike** [comment]
Adding `*.weebly.com` -> `*.editmysite.com` to my whitelist solved the web site edition problem.  
You probably might want to add it to the default whitelist. Thanks for the `ctrl-shift-E` I didn't knew.

I also see that you actively upgrade your module to become a WebExtension. Great job. Thank you.

**Comment by alexander255** [comment]
> Adding `*.weebly.com` -> `*.editmysite.com` to my whitelist solved the web site edition problem.

Thanks for testing this. Based on the log that is exactly what I would have proposed as well. 🙂 

> I also see that you actively upgrade your module to become a WebExtension. Great job. Thank you.

Thanks!

**Comment by alexander255** [comment]
I've just pushed an update to the default whitelist.

Please test to make sure it works as expected:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure you use the default **Whitelist Source** (`http://meh.github.io/smart-referer/whitelist.txt`)
 5. Remove any custom **Allow** rules that are related to this bug
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the *Enable* to re-enable button (this will force a whitelist update)
 8. Check if your page is working now 🙂 

Feel free to close this issue if it works now!

**Comment by chmike** [comment]
It works now. Thank you very much.
