### ISSUE TITLE
https://www.fanatical.com/en/

### ISSUE THREAD

**Issue by denhal** [meh/smart-referer#69]
https://www.fanatical.com/en/ used to be https://www.bundlestars.com/en/
Since the change the website is broken while smart-referer is enabled. I tried to add some custom rules, but can't find the correct domains to make the website work.

**Comment by alexander255** [comment]
Hi and thanks for your report!

Please remember that I have never used this site before, so please provide a detailed explaination / step-by-step guide of performing whatever action is broken on that site.

Also, if you can, please open the network analyser panel (Ctrl+Shift+E) on that site, perform whatever action is broken (if its the entire page then just reload) and upload a screenshot of the result. It should look similar to this (make the panel as large as possible before taking the screenshot, if the content still doesn't fit into the panel, please take one screenshot per page and post all of them):
![screenshot_20171031_203708](https://user-images.githubusercontent.com/246386/32245194-46c45428-be7b-11e7-840d-758f20774af9.png)

Thanks for your help in getting this fixed!

**Comment by denhal** [comment]
![smart-referer-off](https://user-images.githubusercontent.com/12201799/32512746-fb3617b0-c3ef-11e7-8fd8-1e90a2c01203.jpg)
![smart-referer-off-network-1of2](https://user-images.githubusercontent.com/12201799/32512749-fb6a30a4-c3ef-11e7-878f-f41073a34629.jpg)
![smart-referer-off-network-2of2](https://user-images.githubusercontent.com/12201799/32512750-fb8dfe9e-c3ef-11e7-93a4-ba63595fad88.jpg)
![smart-referer-on](https://user-images.githubusercontent.com/12201799/32512751-fbadb16c-c3ef-11e7-9947-bfc19fa3e3f2.jpg)
![smart-referer-on-network-1of1](https://user-images.githubusercontent.com/12201799/32512753-fc7cf904-c3ef-11e7-924b-8978dee88cdf.jpg)

It affects the entire site. See screenshots of site and network traffic with smart-referer both on and off.

**Comment by denhal** [comment]
Still getting used to using Github. Didn't mean to close. The traffic seems to be mixed ipv4 and ipv6 if that will make any difference.

**Comment by alexander255** [comment]
Thanks for your screenshots (including network logs): I saw the breakage and how to fix it almost immediately after that and have pushed an applicable fix (`*.fanatical.com>w2m9492ddv-*.algolianet.com`) to the default whitelist. I need your feedback on whether it works for you now however:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure you use the default **Whitelist Source** (`http://meh.github.io/smart-referer/whitelist.txt`)
 5. Remove any custom **Allow** rules that are related to this bug
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the *Enable* to re-enable button (this will force a whitelist update)
 8. Check if your page is working now 🙂 

After that feel free to close this issue if it works now!

**Comment by denhal** [comment]
Its working now. Thanks for the prompt action.
