### ISSUE TITLE
Allow more than one whitelist source

### ISSUE THREAD

**Issue by crssi** [meh/smart-referer#78]
Does "White list source" accept more than one source?
If it does, what is the delimiter?

What is the extension pull frequency for "White list source"?

Thank you in advance
Cheers

**Comment by alexander255** [comment]
> Does "White list source" accept more than one source?
> If it does, what is the delimiter?

No. This has never been requested as a feature until now. What is your use-case for this?

> What is the extension pull frequency for "White list source"?

24 hours and at every browser start. There is no hidden switch to configure this either, but you can disable updating the whitelist entirely by clearing the whitelist source URL field.

Feel free to ask any further questions!

**Comment by crssi** [comment]
Thank you for your answer for pull frequency.

About the question for more than one source:
I have made the firefox profile for bunch of users... my folks, friends and everyone interested in.
I would like to keep your whitelist in the config and in the same time, when my mother says that player.vimeo.com does not work, to update the custom list very fast (in the same day) and at the same time not to taking special care tracking changes when your list is updated :smile:
At the same time I swear to report breakage to you as I did for `https://github.com/meh/smart-referer/issues/77`

cheers

**Comment by alexander255** [comment]
> I have made the firefox profile for bunch of users... my folks, friends and everyone interested in.
> I would like to keep your whitelist in the config and in the same time, when my mother says that player.vimeo.com does not work, to update the custom list very fast (in the same day) and at the same time not to taking special care tracking changes when your list is updated :smile:

Fair enough, I'm convinced that this may be useful. :slightly_smiling_face: 

This feature (more than one whitelist source) has been implemented in current master. The default whitelist will now be displayed as an on/off checkbox and any number of custom whitelist URLs may be added below: ![screenshot_20180417_235943](https://user-images.githubusercontent.com/246386/38900344-696c23f8-429b-11e8-852e-c4c1018bb92b.png)

A release should follow soonish, but I wanna wait for that other PR if possible.

**Comment by crssi** [comment]
thank you :+1: 
Cheers

**Comment by alexander255** [comment]
I've pushed the changes now! Please check if there are any issues that I haven't found when testing.
Cheers :grin:

**Comment by crssi** [comment]
At the moment I haven't found any problems.

Thank you again
Cheers
