### ISSUE TITLE
openload.co

### ISSUE THREAD

**Issue by SMed79** [meh/smart-referer#79]
Hi,
openload.co (oload.site) video iframe won't load and give you "_file not found error_".

E.g. url where the issue occurs
`https://hdeuropix.io/movie/red-sparrow-online-free-hd-with-subtitles-europix`

**screenshots:**
- http://i.imgur.com/UIk1Ebj.png
- http://i.imgur.com/Kn9ewfY.png

**Fix:**
**source**: _openload.co_
**destination**: _oload.site_

---
smart referer 0.2.3
firefox 59.0.1

**Comment by alexander255** [comment]
Thank you for reporting this and providing the entrie fix, I'm sorry for the late reply here!
Could you check the site again and see if this issue still affects you. When I try to play the example video it works just fine for me and no connection to `oload.site` is ever attempted (according to uBlock). If you are positive that it's still an issue for you I'll merge anyways, but I may ask you to revalidate about once a year.
