### ISSUE TITLE
Bitbucket.org

### ISSUE THREAD

**Issue by tikums** [meh/smart-referer#8]
Bitbucket.org fails with the following error message:

"Forbidden (403)

CSRF verification failed. Request aborted.

You are seeing this message because this HTTPS site requires a 'Referer header' to be sent by your Web browser, but none was sent. This header is required for security reasons, to ensure that your browser is not being hijacked by third parties.

If you have configured your browser to disable 'Referer' headers, please re-enable them, at least for this site, or for HTTPS connections, or for 'same-origin' requests."

Would be nice to have it in the whitelist.

**Comment by alexander255** [comment]
I cannot reproduce this: I created an account, logged out, clicked on the "confirm address" link in the mail they sent me, logged back in, logged out again and logged back in. Even with strict mode enabled I encountered no issues.

Can this issue still be reproduced by anybody?
