### ISSUE TITLE
Add option to notify user when whitelisted item is activated

### ISSUE THREAD

**Issue by vertigo220** [meh/smart-referer#88]
This would keep the user aware of what's going on and prevent referers from the default whitelist from doing things they might not want. The option could even be made more granular by allowing the user to choose whether to receive no notifications, notifications only for default whitelist actions, or notifications for all whitelist actions (default and personal).

**Comment by ntninja** [comment]
This issue has been moved to GitLab: https://gitlab.com/smart-referer/smart-referer/issues/88
