### ISSUE TITLE
Multiple blank items added to "Custom whitelist sources" after update

### ISSUE THREAD

**Issue by anewuser** [meh/smart-referer#89]
I don't have any whitelist source. After updating the extension, multiple empty fields were added to the settings page. This happened with the previous update too.

![screenshot](https://user-images.githubusercontent.com/6733770/39971466-efb1aace-56d1-11e8-80e2-1deecaefdc9a.png)

Smart Referer 0.2.8 
Firefox 60.0
Windows 10

**Comment by alexander255** [comment]
Thank you for your bug report! I could initially believe this but there is indeed a very subtle issue in the code when upgrading from previous versions. I've pushed new code that fixed the upgrade routine as well as cleaning up dead/duplicate entries left by the previous bug in f03944272c5231cd5441a3d3da588d74c3a4b4c8.
This should therefor be fixed the next release and all empty entries should also disappear automatically.

**Comment by alexander255** [comment]
Oh and could you also open bug reports for those whitelist exceptions you added and why you need them?

**Comment by anewuser** [comment]
Thanks for looking into it.

Also, it seems that my exceptions are already part of your default whitelist.
