### ISSUE TITLE
Add right-click menu entry on icon for Preferences Not Working

### ISSUE THREAD

**Issue by B00ze64** [meh/smart-referer#92]
Good day.

Looking for a replacement for RefControl. Smart-Referer is not quite there - having to go to the addOn's preferences (via the about:Addons) to whitelist a site is kinda annoying, a "Whitelist Current Site" option on the icon would be a lot easier to use. Anyway, a good intermediate step is that "Right-Click Option" you have added in last version. Unfortunately, I cannot get it to work on FF52; no matter what I do, when I right-click I get the browser's own menu (i.e. Hide Icon, Customize the toolbar, etc). Is this supposed to work on FF52? I do have some extensions where right-click works...

Thank you.

**Comment by B00ze64** [comment]
Hi Alexander.

I was afraid of that, FF52 WebExtensions APIs are missing a lot of stuff.

Is Waterfox better than Palemoon? Just curious...

Regards,

**Comment by alexander255** [comment]
Palemoon is based on Firefox 24 IIRC and afaik does not support WebExtensions at all (you can still the 0.1.x series of this add-on there through). The publish security updates every now and then, but the core browser engine is essentially unmaintained.

Waterfox is based on Firefox 56 (the last release supporting non-WebExtension add-ons and non-Flash-plugin plugins). They backport security fixes from Firefox 60 ESR on a case by case basis. Support is there for all WebExtension APIs introduced up to Firefox 56 – so almost all APIs that *Smart Referer* uses currently.

Palemoon is already quite far behind on tech, Waterfox is better but their long-term roadmap for keeping it this way is quite unclear as well.

**Comment by B00ze64** [comment]
Thanks! I shall have a look at Waterfox :-) I wonder if they will back-port newer WE APIs, giving us the best of both worlds - XUL and WE. I'll definitively keep an eye on them!

**Comment by alexander255** [comment]
@B00ze64: There are definitely people working on this and appently most 57 APIs have been ported (but not all so they cannot bump the version yet).
