### ISSUE TITLE
Blank icon when profile is copied to another computer

### ISSUE THREAD

**Issue by crssi** [meh/smart-referer#95]
Do you might know why icon goes blank if firefox profile is copied to another computer?
At start of Firefox the icon is there, but shortly after changes to blank.

Thank you, cheers

**Comment by alexander255** [comment]
Could you add details on computer this is (browser name, browser version, operating system name, operating system version)?
Also did you try using the icon color settings in the add-on settings? Maybe the icon is just barely visible / has very little contrast in your current theme?

**Comment by crssi** [comment]
Windows 10, Firefox 60.0.2

Yes, I have tried changing theme, but with no success. When theme is dark, there is just white square.
Funny is that imediatelly after FF is started the icon appears, but a few moments after goes blank.

Cheers

**Comment by crssi** [comment]
Now I feel stupid and blind.

Thank you

**Comment by alexander255** [comment]
Glad it works for you now!
Would you mind elaborating what the issue was for you? Does it work if you choose a custom color in the extension's options?

**Comment by crssi** [comment]
OK... I have found the culprit.
It doesn't matter which theme of FF I use... even default one.
The only option when the icon works is when `Colors of the Default "Dark" & "Light" Themes` is selected under Smart Referer options.
The problem is that every time when I revisit Smart Referer options page this option is auto set to `Custom Color` and the icon goes blank.

**Comment by ntninja** [comment]
This issue has been moved to GitLab: https://gitlab.com/smart-referer/smart-referer/issues/95
