### ISSUE TITLE
Edit exceptions

### ISSUE THREAD

**Issue by vertigo220** [meh/smart-referer#99]
Instead of having to recreate an exception if you make a mistake typing it or want to try something just slightly different, the ability to just edit them would be nice. Definitely low priority, though, as it's not really a big deal. Another nice feature would be a button to switch an exception's source and destination, and maybe one to create a switched copy, to help when figuring out how to get something working.

**Comment by ntninja** [comment]
This issue has been moved to GitLab: https://gitlab.com/smart-referer/smart-referer/issues/99
